# Generated by Django 4.0.5 on 2022-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('flyer', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(default='nan', editable=False, max_length=300, unique=True)),
                ('body', models.TextField()),
                ('tag_one', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_two', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_three', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('feature', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'ordering': ('-posted',),
            },
        ),
    ]
