# Generated by Django 4.0.5 on 2022-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
