# Generated by Django 4.0.5 on 2022-09-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_end_date_alter_program_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='google_form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
