# Generated by Django 4.0.5 on 2022-09-12 08:31

from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_google_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=program.models.generate_id_length, editable=False, max_length=7)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
