# Generated by Django 4.0.5 on 2022-09-12 14:23

from django.db import migrations, models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='code',
            field=models.CharField(default=program.models.generate_id_length, max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
