# Generated by Django 4.0.5 on 2022-10-30 13:45

from django.db import migrations, models
import django.db.models.deletion
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_passcode_code_alter_program_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='code',
            field=models.CharField(blank=True, default=program.models.generate_id_length, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProgramResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('type_of', models.CharField(choices=[('video', 'Video Link'), ('document', 'Document')], max_length=150)),
                ('link', models.URLField(max_length=1000)),
                ('file_title', models.TextField()),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='Program')),
            ],
        ),
    ]
