# Generated by Django 4.0.5 on 2022-10-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_passcode_code_programresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='programresource',
            name='Document_upload',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='programresource',
            name='file_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programresource',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='programresource',
            name='type_of',
            field=models.CharField(choices=[('video', 'Video Link'), ('document', 'Document Upload/link')], max_length=150),
        ),
    ]
